apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/hook: PreSync
spec: {}
  #targetNamespaces:
  #  - ansible-automation-platform