apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ansible-automation-platform-operator.ansible-automation-platfor: ''
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: ansible-automation-platform-operator
  namespace: ansible-automation-platform
spec:
  channel: early-access-cluster-scoped
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: aap-operator.v2.0.1-0.1635283332
