kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-managedclusterset-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'AppLifecycle'
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'AppLifecycle-Admins'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managedclusterset:admin:cluster-lifecycle