kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-cluster-access
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: hypershift-devel
roleRef:
  kind: ClusterRole
  name: pipeline-admin
  apiGroup: rbac.authorization.k8s.io
