kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcm-security-namespace-access
  namespace: hcm-security
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: hcm-security
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:hcm-security'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
