kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-create
rules:
  - verbs:
      - get
      - watch
      - list
      - create
    apiGroups:
      - 'project.openshift.io'
    resources:
      - projects