kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cee-infra-mgmt-namespace-access
  namespace: cee-infra-mgmt
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: cee-infra-mgmt
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:cee-infra-mgmt'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
