---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hibernator-curator
rules:
- apiGroups: ["hive.openshift.io"]
  resources: ["clusterdeployments"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: hibernator-curator
subjects:
- kind: ServiceAccount
  name: hibernator
  namespace: app
roleRef:
  kind: ClusterRole
  name: hibernator-curator
  apiGroup: rbac.authorization.k8s.io