kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-grc-security-kube-public-ns-access
  namespace: kube-public
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: policy-grc
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:acm-grc-security'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
