kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcm-playground-namespace-access
  namespace: hcm-playground
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: hcm
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:hcm-playground'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
