kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-observability-usa-managedclusterset-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'Search'
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'Search-Admin'
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:acm-observability-usa'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managedclusterset:admin:acm-observability-usa